core/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='index'),
    path('contato/', views.contato, name='contato'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cursos/urls.py
from django.urls import path

from . import views

app_name = 'cursos'

urlpatterns = [
    path('', views.cursos, name='cursos'),
    path('<str:slug>/', views.curso, name='curso'),
    path('inscricao/<str:slug>/', views.inscricao, name='inscrever'),
    path('detalhe/<str:slug>/', views.detalhe_curso, name='detalhe'),
    path('anuncio_curso/<str:slug>/', views.anuncio_curso, name='anuncio'),
    path('cancelar_curso/<int:id_curso>/', views.cancelar_curso, name='deletar_curso'),
    path('anuncio_curso/<str:slug>/<int:pk>/', views.comentarios, name='mostrar_aula'),
    path('anuncio_curso/<str:slug>/licoes/', views.licoes, name='licoes'),
    path('anuncio_curso/<str:slug>/licoes/aula/<int:pk>/', views.licao, name='licao'),
    path('anuncio_curso/<str:slug>/material/aula/<int:pk>/', views.material, name='arquivos'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('cursos/', include('cursos.urls', namespace='cursos')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('contas/', include('contas.urls', namespace='contas'))
]

cursos/models.py
from django.db import models
from django.conf import settings
from core.mail import send_mail_temmplate
from django.shortcuts import render, get_object_or_404

# Create your models here.
from django.utils import timezone


class CursoManager(models.Manager):
    def busca(self, query):
        return self.get_queryset().filter(models.Q(nome__icontains=query) | models.Q(descricao__icontains=query))


class Curso(models.Model):

    nome = models.CharField(max_length=150, verbose_name='Nome')
    slug = models.SlugField(verbose_name='Atalho')
    descricao = models.TextField(verbose_name='Descricao', blank=True)
    sobre = models.TextField(verbose_name='Descricao reduzida', blank=True)
    inicio = models.DateField(verbose_name='Data de Inicio', null=True, blank=True)
    imagem = models.ImageField(upload_to='imagens/', verbose_name='Inserir Imagem', null=True, blank=True)
    criado = models.DateTimeField(verbose_name='Criado em', auto_now_add=True)
    modificado = models.DateTimeField(verbose_name='Atualizado em', auto_now=True)

    def __str__(self):
        return self.nome

    def mostrar_imagem(self):
        if self.imagem =='':
            return False
        else:
            return True

    def licoes_disponiveis(self):
        hoje = timezone.now().date()
        return self.licoes.filter(data_disponibilizacao__gte=hoje)


    objects = CursoManager()

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural='Cursos'


class Licao(models.Model):
    nome = models.CharField(verbose_name='Nome', max_length=100)
    descricao = models.TextField(verbose_name='Descrição', blank=True)
    numero = models.IntegerField(verbose_name='Numero da aula', blank=True, default=0)
    data_disponibilizacao = models.DateField(verbose_name='Data disponibilização', blank=True, null=True)

    curso = models.ForeignKey(Curso, verbose_name='Curso', on_delete=models.CASCADE, related_name='licoes')
    data_licao = models.DateTimeField(auto_now_add=True, verbose_name='Criado em')
    atualizado = models.DateTimeField(auto_now=True, verbose_name='Atualizado')

    def __str__(self):
        return self.nome

    def esta_disponivel(self):
        if self.data_disponibilizacao:
            hoje = timezone.now().date()
            return self.data_disponibilizacao >= hoje
        return False

    class Meta:
        verbose_name = 'Aula'
        verbose_name_plural='Aulas'
        ordering = ['numero']

class Material(models.Model):
    nome = models.CharField(verbose_name='Nome', max_length=100)
    midia = models.TextField(verbose_name='Midia', blank=True)
    arquivo = models.FileField(verbose_name='Arquivo', blank=True, upload_to='material/licao', null=True)

    licao = models.ForeignKey(Licao, verbose_name='Licao', on_delete=models.CASCADE, related_name='materiais')

    def is_midia(self):
        return bool(self.midia)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Material'
        verbose_name_plural='Materiais'


class Inscricao(models.Model):
    STATUS_CURSO = (
        (0, 'Pendente'),
        (1, 'Aprovado'),
        (2, 'Bloqueado'),
        (3, 'Cancelado'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuario', related_name='inscricao', on_delete=models.CASCADE)
    curso = models.ForeignKey(Curso, verbose_name='Curso', related_name='inscricao', on_delete=models.CASCADE)
    status = models.IntegerField(verbose_name='Situacao', choices=STATUS_CURSO, blank=True, default=1)

    data_inscricao = models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscricao')
    atualizado = models.DateTimeField(auto_now=True, verbose_name='Atualizado')

    def __str__(self):
        return self.curso.nome

    def ativar(self):
        self.status = 1
        self.save()

    def aprovado(self):
        return self.status == 1

    class Meta:
        verbose_name = 'Inscrição'
        verbose_name_plural = 'Inscrições'
        constraints = [
            models.UniqueConstraint(fields=['user', 'curso'], name='unique_curso')
        ]

class AnuncioCurso(models.Model):
    curso = models.ForeignKey(Curso, verbose_name='Curso', on_delete=models.CASCADE, related_name='usuario_anuncios')
    titulo = models.CharField(verbose_name='Titulo', max_length=100)
    conteudo = models.TextField('Conteudo')

    data_inscricao = models.DateTimeField(auto_now_add=True, verbose_name='Criado em')
    atualizado = models.DateTimeField(auto_now=True, verbose_name='Atualizado')

    def __str__(self):
        return self.titulo

    class Meta:
        verbose_name = 'Anuncio_Curso'
        verbose_name_plural='Anuncios_Cursos'
        ordering = ['-data_inscricao']
        db_table = 'comentarios_curso'

class Comentarios(models.Model):
    anuncio_curso = models.ForeignKey(AnuncioCurso, verbose_name="Anuncio", related_name='comentarios', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuario', on_delete=models.CASCADE)
    comentario = models.TextField(verbose_name='Comentario')

    data_inscricao = models.DateTimeField(auto_now_add=True, verbose_name='Criado em')
    atualizado = models.DateTimeField(auto_now=True, verbose_name='Atualizado')

    def __str__(self):
        return str(self.anuncio_curso)

    class Meta:
        verbose_name = 'Comentario'
        verbose_name_plural='Comentarios'
        ordering = ['-data_inscricao']





# def post_save_inscricao(instance, created, ** kwargs):
#     if created:
#             subject = instance.curso
#             context= {
#                 'inscricao': instance
#             }
#             inscrito  = Inscricao.objects.filter(curso=instance.curso)[:1]
#             recipient_list=[inscrito.user.email]
#             send_mail_temmplate(subject, 'cursos/inscricao_mail.html', context, recipient_list)
#
#
# models.signals.post_save.connect(
#     post_save_inscricao, sender=Inscricao, dispatch_uid='post_save_inscricao'
# )

cursos/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings
from core.mail import send_mail_temmplate

from .models import Comentarios

class ContatoCurso(forms.Form):
    nome = forms.CharField(label='Nome', max_length=100)
    e_mail = forms.EmailField(label='E-mail')
    mensagem = forms.CharField(label='Mensagem/Dúvida', widget=forms.Textarea)

    def send_mail(self, curso):
        subject = '{curso} contato'.format(
            curso=curso
        )
        context = {
            'nome': self.cleaned_data['nome'],
            'e_mail': self.cleaned_data['e_mail'],
            'mensagem': self.cleaned_data['mensagem']
        }
        template_name = 'cursos/email_contato.html'
        send_mail_temmplate(subject,template_name,context, [settings.CONTACT_EMAIL])


class ComentariosForm(forms.ModelForm):
    class Meta:
        model = Comentarios
        fields = ['comentario']

cursos/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Curso, Inscricao, AnuncioCurso, Licao, Material
from .forms import ContatoCurso, ComentariosForm
from .decorators import incricao_requerida


def cursos(request):
    cursos = Curso.objects.all()
    contexto = {'cursos':cursos}
    return render(request, 'cursos/cursos.html', contexto)

@login_required
def curso(request, slug):
    cursinho = Curso.objects.get(slug=slug)
    contexto = {}
    if request.method == 'POST':
        form = ContatoCurso(request.POST)
        if form.is_valid():
            form.send_mail(cursinho)
            envio = True
            contexto['envio'] = envio
            form = ContatoCurso()
    else:
        form = ContatoCurso()
    contexto['form'] = form
    contexto['curso'] = cursinho
    return render(request, 'cursos/curso.html', contexto)

@login_required
def inscricao(request, slug):
    curso = get_object_or_404(Curso, slug=slug)

    inscrever, criado = Inscricao.objects.get_or_create(user=request.user, curso=curso)

    if criado:
        messages.success(request, 'Inscrição realizada com sucesso!')
    #     inscrever.ativar()
        return redirect('contas:painel')
    else:
        messages.info(request, 'Você ja está incrito nesse curso.')
        return redirect('contas:painel')

@login_required
@incricao_requerida
def detalhe_curso(request, slug):
    curso = request.curso
    return render(request, 'cursos/detalhe_curso.html', {'inscrito': curso})

@login_required
@incricao_requerida
def anuncio_curso(request, slug):
    curso = request.curso
    return render(request, 'cursos/anuncio_curso.html', {'curso':curso, 'anuncios': curso.usuario_anuncios.all()})

@login_required
def cancelar_curso(request, id_curso):
    curso = get_object_or_404(Curso, id=id_curso)
    inscricao = get_object_or_404(Inscricao, user=request.user, curso=curso)
    if request.method == 'POST':
        inscricao.delete()
        messages.warning(request, 'Você cancelou a inscrição do curso {}!'.format(curso.nome))
        return redirect('contas:painel')

    return render(request, 'contas/cancelar_curso.html', {'curso':curso, 'inscricao':inscricao})

@login_required
@incricao_requerida
def comentarios(request, slug, pk):
    curso1 = request.curso
    comentario = get_object_or_404(curso1.usuario_anuncios.all(), pk=pk)
    form = ComentariosForm(request.POST or None)
    if form.is_valid():
        coment = form.save(commit=False)
        coment.user = request.user
        coment.anuncio_curso = get_object_or_404(AnuncioCurso, curso=curso1)
        coment.save()
        form = ComentariosForm()
        messages.success(request, 'Comentário enviado com sucesso')
    contexto = {'curso':curso1, 'comentario':comentario, 'form': form}
    return render(request, 'cursos/mostrar_aula.html', contexto)

@login_required
@incricao_requerida
def licoes(request, slug):
    curso = request.curso
    return render(request, 'cursos/licoes.html', {'curso':curso})

@login_required
@incricao_requerida
def licoes(request, slug):
    curso=request.curso
    licoes = curso.licoes_disponiveis()
    if request.user.is_staff:
        licoes = curso.licoes.all()
    contexto = {
        'curso': curso,
        'licoes': licoes
    }
    return render(request, 'cursos/licoes.html', contexto)

@login_required
@incricao_requerida
def licao(request, slug, pk):
    curso=request.curso
    licao = get_object_or_404(Licao, pk=pk, curso=curso)
    material = Material.objects.filter(licao=licao)

    if not request.user.is_staff and not licao.esta_disponivel():
        messages.error(request, 'Aula Indisponivel')
        return redirect('cursos:licoes', slug=curso.slug)

    contexto = {'curso': curso, 'licao': licao, 'material':material}
    return render(request, 'cursos/licao.html', contexto)

@login_required
@incricao_requerida
def material(request, slug, pk):
    curso = request.curso
    material = get_object_or_404(Material, pk=pk, licao__curso=curso)
    licao = material.licao

    if not request.user.is_staff and not licao.esta_disponivel():
        messages.error(request, 'Material Indisponivel')
        return redirect('cursos:licao', slug=curso.slug, pk=licao.pk)
    if not material.is_midia():
        return redirect(material.arquivo.url)
    contexto ={'curso' : curso, 'licao':licao, 'material':material}
    return render(request, 'cursos/arquivo.html', contexto)

cursos/templates/cursos/anuncio_curso.html
{% extends 'contas/admin_cursos.html'%}
{% block titulo %}<title>Painel Aulas</title>{% endblock %}
{% block breadcrumb %}
{{block.super}}
<li class="breadcrumb-item"><a href="{% url 'cursos:anuncio' curso.slug %}">Curso</a></li>
{% endblock %}
{% block tema %}
<h1 class="text-center">Anuncio das Aulas</h1>
{% endblock %}

{% block menu_opcoes %}
<div class="list-group">
    <li class="list-group-item text-center">
        <h5><b>{{curso}}</b></h5>
    </li>
    <a href="{% url 'cursos:licoes' curso.slug %}" class="list-group-item list-group-item-action">
        <i class="fas fa-video"></i>
        Aulas e Materiais
    </a>
    <a href="#" class="list-group-item list-group-item-action">
        <i class="fas fa-info-circle"></i>
        Informações
    </a>
    <a href="#" class="list-group-item list-group-item-action">
        <i class="fas fa-envelope"></i>
        Anuncios
    </a>
    <a href="#" class="list-group-item list-group-item-action">
        <i class="far fa-comments"></i>
        Forum de Dúvidas
    </a>
</div>
{{block.super}}
{% endblock %}

{% block estudante %}
<div class="container">
    {% if anuncios %}
    {% for anuncio in anuncios %}
    <a href="{% url 'cursos:mostrar_aula' curso.slug anuncio.pk %}">
    <h3 class="title text-center">{{anuncio.titulo}}</h3>
    </a>
    {{anuncio.conteudo | linebreaks|truncatewords:'200'}} <a href="{% url 'cursos:mostrar_aula' curso.slug anuncio.pk %}" type="button" class="btn btn-sm btn-info">Continuar...</a>
    <div class="coments">
        <a href="{% url 'cursos:mostrar_aula' curso.slug anuncio.pk %}">
        {% with contar=anuncio.comentarios.count %}
        <i class="far fa-comments"></i>
        {{contar}}
        Comentário{{contar | pluralize}}
        {% endwith %}
        </a>
    </div>
    {% endfor %}
    {% else %}
    <p class="text-danger">Não a anuncios sobre o curso.</p>
    {% endif %}
</div>
{% endblock %}

cursos/templates/cursos/arquivo.html
{% extends 'cursos/licoes.html'%}
{% load static %}
{% load bootstrap4 %}
{% block titulo %}<title>{{material}}</title>{% endblock %}
{% block breadcrumb %}
{{block.super}}
<li class="breadcrumb-item"><a href="{% url 'cursos:licao' curso.slug licao.pk %}">{{licao}}</a></li>
<li class="breadcrumb-item"><a href="{% url 'cursos:arquivos' curso.slug material.pk %}">{{material}}</a></li>
{% endblock %}
{% block tema %}
<h1 class="text-center">Video Aula</h1>
{% endblock %}
{% block estudante %}
<div class="container">
    <div class="row">
        {{material.midia|safe}}
    </div>
</div>
{% endblock %}

cursos/templates/cursos/curso.html
{% extends 'base/base.html' %}
{% load static %}
{% block titulo %}<title>Curso</title>{% endblock %}
{% block conteudo %}
<div class="container-fluid">
    <div class="jumbotron jumbotron-fluid bg-light">
      <div class="container">
        <h1 class="text-center">{{curso.nome}}</h1>
        <p class="text-center">{{curso.sobre}}</p>
          <p class="text-center"><small>Criado: {{curso.criado.date}}</small></p>
          <p class="text-center">
          <a href="{% url 'cursos:inscrever' curso.slug %}" class="text-center"><button type="button" class="btn btn-info">Inscreva-se</button></a>
          </p>
      </div>
    </div>
</div>
<div class="container">
    <div class="container-fluid">
        <h2>SOBRE O CURSO</h2>

        {% if curso.mostrar_imagem %}
            <img class="rounded float-left" style="margin:15px; margin-left:0px;" src="{{curso.imagem.url}}">
        {% else %}
            <img class="rounded float-left" src="{% static 'cursos/image/imagem.png' %}">
        {% endif %}
        <p><a href="#contato" class="btn btn-blue-grey">Comente</a></p>
        {{curso.descricao | linebreaks}}
        <p><small>Atualizado: {{curso.modificado.date}}</small></p>
    </div>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6">
        <h3>Tire suas dúvidas sobre o curso</h3>
        {% if envio %}
        <h5>Formulário enviado com sucesso!</h5>
        {% endif %}
      <div class="form-wrapper">
        <form class="form" method="post" action="#contato" id="contato">
            {% csrf_token %}
            <table>
                <tbody>
                    <tr>
                        <td>
                            {{form.as_table}}
                        </td>
                    </tr>
                </tbody>
            </table>
            <button type="submit" class="btn btn-info">Enviar</button>
        </form>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

cursos/templates/cursos/cursos.html
{% extends 'base/base.html' %}
{% load static %}
{% block titulo %}<title>Cursos</title>{% endblock %}
{% block conteudo %}
<div class="container">

      <!-- Page Heading -->
      <h2 class="my-4">Listagem de Cursos</h2>

       {% for curso in cursos %}
      <!-- Project One -->
      <div class="row">
        <div class="col-md-5">
          {% if curso.mostrar_imagem %}
          <a href="{% url 'cursos:curso' curso.slug %}">
            <img class="img-fluid rounded mb-3 mb-md-0" src="{{curso.imagem.url}}" alt="">
          </a>
          {% else %}
            <a href="{% url 'cursos:curso' curso.slug %}">
            <img class="img-fluid rounded mb-3 mb-md-0" src="{% static 'cursos/image/imagem.png' %}" alt="">
          </a>
           {% endif %}
        </div>
        <div class="col-md-7">
          <h3>{{curso.nome }}</h3>
          {{curso.descricao | linebreaks | slice:":450"}}...
          <div class="row">
              <div class="col-md-6">
                  <a class="btn btn-primary" href="{% url 'cursos:curso' curso.slug %}">Visualizar Curso</a>
              </div>
              <div class="offset-md-2 col-md-4">
                  <small><b>Criado: </b>{{curso.criado.date}}</small>
              </div>
          </div>
        </div>
      </div>
      <!-- /.row -->
      <hr>
      {% endfor %}
      <!-- Pagination -->
      <ul class="pagination justify-content-center">
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">1</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      </ul>

    </div>
{% endblock %}

cursos/templates/cursos/detalhe_curso.html
{% extends 'contas/admin_cursos.html'%}
{% block estudante %}
    <br><br>
    <div class="container">
        <div class="row">
       <!--Panel-->
        <div class="card">
            <div class=" card-header light-color">
                <h3><b>{{inscrito}}</b></h3>
            </div>
            <div class="card-body">
                <h5 class="card-title">Iniciado em: {{inscrito.criado.date}}</h5>
                <h4 class="card-text">{{inscrito.descricao |linebreaks | slice:":500"}}</h4>
            </div>
            <div class="card-footer text-muted light-color">
                <a href="{% url 'cursos:anuncio' inscrito.slug %}" class="btn btn-info btn-sm">Acessar</a>
	<!-- Button HTML (to Trigger Modal) -->
	<a href="#myModal" class="btn btn-danger btn-sm" data-toggle="modal">Cancelar</a>

<!-- Modal HTML -->
<div id="myModal" class="modal fade">
	<div class="modal-dialog modal-confirm">
		<div class="modal-content">
			<div class="modal-header">
				<div class="icon-box">
					<i class="material-icons">&#xE5CD;</i>
				</div>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			</div>
            <h4 class="modal-title">Excluir Curso?</h4>
			<div class="modal-body">
				<h5>Deseja realmente excluir o curso</h5><br>
                <h6>{{inscrito}}?</h6>
			</div>
			<div class="modal-footer">
                <form method="post" action="{% url 'cursos:deletar_curso' inscrito.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Deletar</button>
                    <button type="button" class="btn btn-info" data-dismiss="modal">Cancelar</button>
                </form>
			</div>
		</div>
	</div>
</div>
            </div>
        </div>
        <!--/.Panel-->
        </div>
    </div>
{% endblock %}

cursos/templates/cursos/email_contato.html
<p><strong>Nome</strong>: {{nome}}</p>
<p><strong>E-mail</strong>: {{e_mail}}</p>
{{mensagem | linebreaks}}

cursos/templates/cursos/inscricao_mail.html
{{inscricao.curso}}

cursos/templates/cursos/inscricoes.html
{% extends 'base/base.html' %}
{% load static %}
{% block titulo %}<title>Cursos</title>{% endblock %}
{% block conteudo %}
<div class="container">
      <!-- Page Heading -->
      <h2 class="my-4">Listagem de Cursos</h2>

       {% for curso in cursos %}
      <!-- Project One -->
      <div class="row">
        <div class="col-md-5">
          {% if curso.mostrar_imagem %}
          <a href="{% url 'cursos:curso' curso.slug %}">
            <img class="img-fluid rounded mb-3 mb-md-0" src="{{curso.imagem.url}}" alt="">
          </a>
          {% else %}
            <a href="{% url 'cursos:curso' curso.slug %}">
            <img class="img-fluid rounded mb-3 mb-md-0" src="{% static 'cursos/image/imagem.png' %}" alt="">
          </a>
           {% endif %}
        </div>
        <div class="col-md-7">
          <h3>{{curso.nome }}</h3>
          {{curso.descricao | linebreaks | slice:":450"}}...
          <div class="row">
              <div class="col-md-6">
                  <a class="btn btn-primary" href="{% url 'cursos:curso' curso.slug %}">Visualizar Curso</a>
              </div>
              <div class="offset-md-2 col-md-4">
                  <small><b>Criado: </b>{{curso.criado.date}}</small>
              </div>
          </div>
        </div>
      </div>
      <!-- /.row -->
      <hr>
      {% endfor %}
      <!-- Pagination -->
      <ul class="pagination justify-content-center">
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">1</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      </ul>

    </div>
{% endblock %}

cursos/templates/cursos/licao.html
{% extends 'cursos/licoes.html'%}
{% load static %}
{% load bootstrap4 %}
{% block titulo %}<title>{{curso}}</title>{% endblock %}
{% block breadcrumb %}
{{block.super}}
<li class="breadcrumb-item"><a href="{% url 'cursos:licao' curso.slug licao.pk %}">{{licao}}</a></li>
{% endblock %}
{% block tema %}
<h1 class="text-center">Aulas</h1>
{% endblock %}
{% block estudante %}
<div class="container">
    <div class="row">
        <div class="card card-cascade wider reverse">
            <div class="card-body card-body-cascade text-center">

                <h4 class="card-title"><strong>{{licao}}</strong></h4>
                <p class="card-text">
                    {{licao.descricao}}
                </p>
                <table class="table">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Material</th>
                        <th scope="col">Ação</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for material in licao.materiais.all %}
                    {% if material.is_midia %}
                    <tr>
                        <th scope="row">Video</th>
                        <td>{{material}}</td>
                        <td><a href="{% url 'cursos:arquivos' curso.slug material.pk %}" class="text-info"><i class="fas fa-video"></i></a></td>
                    </tr>
                    {% else %}
                    <tr>
                        <th scope="row">Documento</th>
                        <td>{{material}}</td>
                        <td><a target="_blank" href="{{material.arquivo.url}}" class="text-danger"><i class="fas fa-file-pdf"></i></a></td>
                    </tr>
                    {% endif %}
                    {% empty %}
                    <p class="text-danger">Nenhum material de estudo encontrado</p>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<!--    <div class="coments">-->
<!--        <a href="#">-->
<!--        {% with contar=anuncio.comentarios.count %}-->
<!--        <i class="far fa-comments"></i>-->
<!--        {{contar}}-->
<!--        Comentário{{contar | pluralize}}-->
<!--        {% endwith %}-->
<!--        </a>-->
<!--    </div>-->
    <!-- Card -->
</div>
{% endblock %}

cursos/templates/cursos/licoes.html
{% extends 'cursos/anuncio_curso.html'%}
{% load static %}
{% load bootstrap4 %}
{% block titulo %}<title>{{curso}}</title>{% endblock %}
{% block breadcrumb %}
{{block.super}}
<li class="breadcrumb-item"><a href="{% url 'cursos:licoes' curso.slug%}">Lições</a></li>
{% endblock %}
{% block tema %}
<h1 class="text-center">Aulas</h1>
{% endblock %}
{% block estudante %}
<div class="container">
    <div class="row">
        {% for licao in licoes %}
        <div class="card card-cascade wider reverse">
            <div class="card-body card-body-cascade text-center">

                <h4 class="card-title"><strong>{{licao}}</strong></h4>
                <p class="card-text">
                    {{licao.descricao|truncatewords:'60'}}
                </p>
                <p>
                    <a href="{% url 'cursos:licao' curso.slug licao.pk %}"><i class="far fa-eye"></i> Acessar Aula</a>
                </p>
            </div>
        </div><br>
        {% empty %}
        <p>Nenhuma Aula Cadastrada</p>
        {% endfor %}
    </div>
<!--    <div class="coments">-->
<!--        <a href="#">-->
<!--        {% with contar=anuncio.comentarios.count %}-->
<!--        <i class="far fa-comments"></i>-->
<!--        {{contar}}-->
<!--        Comentário{{contar | pluralize}}-->
<!--        {% endwith %}-->
<!--        </a>-->
<!--    </div>-->
    <!-- Card -->
</div>
{% endblock %}