contas/urls.py
from django.urls import path
from . import views

app_name = 'contas'

urlpatterns = [
    path('', views.painel, name='painel'),
    path('editar/', views.editar, name='editar'),
    path('senha/', views.senha, name='senha'),
    path('cadastre-se/', views.cadastrar.as_view(), name='novo'),
]

core/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='index'),
    path('contato/', views.contato, name='contato'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cursos/urls.py
from django.urls import path

from . import views

app_name = 'cursos'

urlpatterns = [
    path('', views.cursos, name='cursos'),
    path('<str:slug>/', views.curso, name='curso'),
    path('inscricao/<str:slug>/', views.inscricao, name='inscrever'),
    path('detalhe/<str:slug>/', views.detalhe_curso, name='detalhe'),
    path('anuncio_curso/<str:slug>/', views.anuncio_curso, name='anuncio'),
    path('cancelar_curso/<int:id_curso>/', views.cancelar_curso, name='deletar_curso'),
    path('anuncio_curso/<str:slug>/<int:pk>/', views.comentarios, name='mostrar_aula'),
    path('anuncio_curso/<str:slug>/licoes/', views.licoes, name='licoes'),
    path('anuncio_curso/<str:slug>/licoes/aula/<int:pk>/', views.licao, name='licao'),
    path('anuncio_curso/<str:slug>/material/aula/<int:pk>/', views.material, name='arquivos'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('cursos/', include('cursos.urls', namespace='cursos')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('contas/', include('contas.urls', namespace='contas'))
]

core/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def home(request):
    return render(request, 'core/index.html')

def contato(request):
    return render(request, 'core/contato.html')

core/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    {% block titulo %}<title></title>{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.14.0/css/mdb.min.css" rel="stylesheet">
    <!-- JQuery -->

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="{% static 'core/css/estilo.css' %}">

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.14.0/js/mdb.min.js"></script>
    <script src="https://kit.fontawesome.com/yourcode.js"></script>

    {% block estilo %}{% endblock %}
</head>
<body>
    {% include 'base/head.html' %}
     <div>
        {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show" {% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
				  <strong>{{message}}</strong>
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				  </button>
				</div>
        {% endfor %}
<!--        <ul class="messages">-->
<!--            {% for message in messages %}-->
<!--            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>-->
<!--                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}-->
<!--                {{ message }}-->
<!--            </li>-->
<!--            {% endfor %}-->
<!--        </ul>-->
    </div>
        {% block conteudo %}

        {% endblock %}

</body>
</html>

core/templates/base/footer.html
<!-- Footer -->
<footer class="page-footer font-small info-color">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="#">S2V2 - Desenvolvimento de soluções para a web</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

core/templates/base/head.html
<nav class="mb-1 navbar navbar-expand-lg navbar-dark info-color">
  <a class="navbar-brand" href="{% url 'core:index' %}">Simplemooc</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
    aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:index' %}">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cursos:cursos' %}">Cursos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:contato' %}">Contato</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-3331" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">Dropdown
        </a>
        <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-3331">
          <a class="dropdown-item" href="#">Painel de administração</a>
          <a class="dropdown-item" href="#">Admin</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto nav-flex-icons">
      <li class="nav-item">
        <a class="nav-link waves-effect waves-light">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link waves-effect waves-light">
          <i class="fab fa-facebook"></i>
        </a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link waves-effect waves-light">
          Olá, {{user.username}}
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right dropdown-default"
          aria-labelledby="navbarDropdownMenuLink-333">
          <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
          <a class="dropdown-item" href="{% url 'contas:painel' %}">Painel</a>
        </div>
      </li>
      {% else %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-33" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right dropdown-default"
          aria-labelledby="navbarDropdownMenuLink-33">
          <a class="dropdown-item" href="{% url 'login' %}">Entrar</a>
          <a class="dropdown-item" href="{% url 'contas:novo' %}">Cadastrar</a>

        </div>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
<!--/.Navbar -->

<!--
<nav class="navbar navbar-expand-sm bg-light navbar-light sticky-top">
  <a class="navbar-brand" href="{% url 'core:index' %}">SIMPLE MOOC</a>
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'core:index' %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'cursos:cursos' %}">Cursos</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'core:contato' %}">Contato</a>
    </li>
        <li class="nav-item">
      <a class="nav-link" href="#">Entrar</a>
    </li>
  </ul>
</nav>
-->