contas/urls.py
from django.urls import path
from . import views

app_name = 'contas'

urlpatterns = [
    path('', views.painel, name='painel'),
    path('editar/', views.editar, name='editar'),
    path('senha/', views.senha, name='senha'),
    path('cadastre-se/', views.cadastrar.as_view(), name='novo'),
]

core/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='index'),
    path('contato/', views.contato, name='contato'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cursos/urls.py
from django.urls import path

from . import views

app_name = 'cursos'

urlpatterns = [
    path('', views.cursos, name='cursos'),
    path('<str:slug>/', views.curso, name='curso'),
    path('inscricao/<str:slug>/', views.inscricao, name='inscrever'),
    path('detalhe/<str:slug>/', views.detalhe_curso, name='detalhe'),
    path('anuncio_curso/<str:slug>/', views.anuncio_curso, name='anuncio'),
    path('cancelar_curso/<int:id_curso>/', views.cancelar_curso, name='deletar_curso'),
    path('anuncio_curso/<str:slug>/<int:pk>/', views.comentarios, name='mostrar_aula'),
    path('anuncio_curso/<str:slug>/licoes/', views.licoes, name='licoes'),
    path('anuncio_curso/<str:slug>/licoes/aula/<int:pk>/', views.licao, name='licao'),
    path('anuncio_curso/<str:slug>/material/aula/<int:pk>/', views.material, name='arquivos'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('cursos/', include('cursos.urls', namespace='cursos')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('contas/', include('contas.urls', namespace='contas'))
]

contas/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

SEXO = [
    ('M', 'Masculino'),
    ('F', 'Feminino'),
]

class Aluno(AbstractUser):
    nome = models.CharField(verbose_name='Nome', max_length=100)
    sexo = models.CharField(verbose_name='Sexo', max_length=20, choices=SEXO)
    cpf = models.CharField(verbose_name='CPF', max_length=11)
    escolaridade = models.CharField(verbose_name='Escolaridade', max_length=50)
    profissao = models.CharField(verbose_name='Profissão', max_length=70)
    cadastrado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True, verbose_name='ALterado')

    def __str__(self):
        return self.nome


class ResetSenha(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuario', on_delete=models.CASCADE, related_name='resets')
    key = models.CharField(verbose_name='Chave', max_length=100, unique=True)
    criado = models.DateTimeField(auto_now_add=True, verbose_name='Criado em', )
    confirmado = models.BooleanField(default=False, blank=True, verbose_name='Confirmado?')

    def __str__(self):
        return self.user + ' em '+ self.criado

    class Meta:
        verbose_name = 'Nova Senha'
        verbose_name_plural = 'Novas Senhas'
        ordering = ['-criado']

contas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

from .models import Aluno


# class EditeUserForm(forms.ModelForm):
#
#     def clean_email(self):
#         email = self.cleaned_data['email']
#         queryset = User.objects.filter(email=email).exclude(pk=self.instance.pk)
#         if queryset.exists():
#             raise forms.ValidationError('Este email ja foi cadastrado!')
#         else:
#             return email
#
#     class Meta:
#         model = User
#         fields = ['username', 'email']
#
# class EditarAluno(forms.ModelForm):
#
#     class Meta:
#         model = Aluno
#         fields = ['nome', 'sexo', 'cpf', 'escolaridade', 'profissao']
#
# class AlunoForm(forms.ModelForm):
#     class Meta:
#         model = Aluno
#         fields = ['nome', 'sexo', 'cpf', 'escolaridade', 'profissao']
#
# class UserForm(forms.ModelForm):
#     password = forms.CharField(max_length=32, widget=forms.PasswordInput)
#
#     def clean_email(self):
#         email = self.cleaned_data['email']
#         queryset = User.objects.filter(email=email).exclude(pk=self.instance.pk)
#         if queryset.exists():
#             raise forms.ValidationError('Este email ja foi cadastrado!')
#         else:
#             return email
#
#     class Meta:
#         model = User
#         fields = ['username', 'password', 'email']

class CriarAluno(UserCreationForm):
    def clean_email(self):
        email = self.cleaned_data['email']
        queryset = Aluno.objects.filter(email=email)
        if queryset.exists():
            raise forms.ValidationError('Este email ja foi cadastrado!')
        else:
            return email
    class Meta(UserCreationForm):
        model = Aluno
        fields = ('nome', 'email', 'sexo', 'cpf', 'escolaridade', 'profissao', 'username')

class EditarAluno(UserChangeForm):
    def clean_email(self):
        email = self.cleaned_data['email']
        queryset = Aluno.objects.filter(email=email).exclude(pk=self.instance.pk)
        if queryset.exists():
            raise forms.ValidationError('Este email ja foi cadastrado!')
        else:
            return email
    class Meta(UserChangeForm):
        model = Aluno
        fields = ('nome', 'email', 'sexo', 'cpf', 'escolaridade', 'profissao', 'username')

contas/views.py
from django.contrib import messages
from django.shortcuts import render
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeForm
from .forms import CriarAluno, EditarAluno
# Create your views here.
from django.views.generic import CreateView
#Resolveu o erro abaixo
#Attempted relative import beyond toplevel package django project on make migrations
from cursos.models import Curso, Inscricao
from django.http import HttpResponse


@login_required
def painel(request):
    cursus = Inscricao.objects.filter(user=request.user)
    return render(request, 'contas/admin_cursos.html', {'cursos':cursus})

@login_required
def senha(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Senha atualizada com sucesso!')
#            return redirect('/account/profile')
    else:
        form = PasswordChangeForm(request.user)
    contexto = {'form':form}
    return render(request, 'contas/senha.html', contexto)

class cadastrar(CreateView):
    form_class = CriarAluno
    success_url = ('/accounts/login/')
    context_object_name = 'form'
    template_name = 'contas/novo.html'

@login_required
def editar(request):
    if request.method == 'POST':
        form = EditarAluno(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            form = EditarAluno(instance=request.user)
            messages.success(request, 'Informações atualizadas com sucesso!')
    else:
        form = EditarAluno(instance=request.user)
    contexto = {'form': form}
    return render(request, 'contas/edit.html', contexto)

contas/templates/contas/admin_cursos.html
{% extends 'base/base.html' %}
{% load static %}
{% load contas_tags %}
{% block titulo %}<title>Painel Cursos</title>{% endblock %}
<link rel="stylesheet" type="text/css" href="{% static 'contas/css/cursos.css' %}">
{% block conteudo %}

<ul class="breadcrumb">
	{% block breadcrumb %}
  	<li class="breadcrumb-item"><a href="{% url 'contas:painel' %}">Painel</a></li>
	{% endblock %}
</ul>
{% block tema %}
<h1 class="text-center">Painel do Estudante</h1>
{% endblock %}
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-4">
			<!--team-1-->
			<div class="col-sm-12">
				{% block menu_opcoes %}
                {% inscricoes user %}
			  <div class="list-group">
                <h3 class="list-group-item">Configurações de Conta</h3>
				<a href="{% url 'contas:editar'%}" class="list-group-item list-group-item-action">
                    <i class="fas fa-user-edit"></i>
                    Editar Informações
                </a>
				<a href="{% url 'contas:senha' %}" class="list-group-item list-group-item-action">
                    <i class="fas fa-lock"></i>
                    Editar Senha
                </a>
				<a href="#" class="list-group-item list-group-item-action">
                    <i class="fas fa-book-open"></i>
                    Editar Cursos
                </a>
			  </div>
				{% endblock %}
			</div>
			</div>
			<!--team-2-->
			<div class="col-md-8">
				{% block estudante %}

				{% endblock %}
			</div>
		</div>
	</div>
{% endblock %}

contas/templates/contas/anuncio_curso.html
{% extends 'contas/admin_cursos.html'%}
{% block titulo %}<title>Painel Aulas</title>{% endblock %}
{% block breadcrumb %}
{{block.super}}
<li class="breadcrumb-item"><a href="{% url 'cursos:anuncio' curso.slug %}">Aulas Curso</a></li>
{% endblock %}
{% block tema %}
<h1 class="text-center">Painel das Aulas</h1>
{% endblock %}

{% block menu_opcoes %}
<div class="list-group">
    <li class="list-group-item text-center">
        <h5><b>{{curso}}</b></h5>
    </li>
    <a href="#" class="list-group-item list-group-item-action">
        <i class="fas fa-video"></i>
        Aulas e Materiais
    </a>
    <a href="#" class="list-group-item list-group-item-action">
        <i class="fas fa-info-circle"></i>
        Informações
    </a>
    <a href="#" class="list-group-item list-group-item-action">
        <i class="fas fa-envelope"></i>
        Anuncios
    </a>
    <a href="#" class="list-group-item list-group-item-action">
        <i class="far fa-comments"></i>
        Forum de Dúvidas
    </a>
</div>
{{block.super}}
{% endblock %}

{% block estudante %}

{% endblock %}

contas/templates/contas/edit.html
{% extends 'contas/admin_cursos.html'%}
{% load bootstrap4 %}
{% block breadcrumb %}
{{block.super}}
<li class="breadcrumb-item"><a href="{% url 'contas:editar' %}">Editar</a></li>
{% endblock %}
{% block tema %}
<h1 class="text-center">Editar Perfil</h1>
{% endblock %}
{% block estudante %}
    <div class="row">
        <div class="offset-1 col-md-7">
            <form method="post" action="#">
                {% csrf_token %}
                {% if sucess %}
                <h3 class="text-success">Informções alteradas com sucesso!</h3>
                {% endif %}
                {% bootstrap_form form layout='inline'%}
                {% buttons %}
                    <button type="submit" class="btn btn-success">Salvar</button>
                    <a href="{% url 'contas:painel' %}"><button type="button" class="btn btn-danger">Cancelar</button></a>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

contas/templates/contas/novo.html
{% extends 'base/base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block titulo %}<title>Cadastrar</title>{% endblock %}
{% block conteudo %}
<div class="container-fluid">
    <div class="row bg-light">

        <div class="col-md-4">
        </div>
        <div class="col-md-4 bg-white" style="margin-top:60px; margin-bottom:150px;">
            <!-- Default form login -->
            <form method="post" class="text-center border border-light p-5" action="{% url 'contas:novo' %}">
                {% csrf_token %}
                {% bootstrap_form form layout='inline' %}
                <!-- Sign in button -->
                {% buttons %}
                <button class="btn btn-info btn-block my-4" type="submit">Cadastrar</button>
                {% endbuttons %}
            </form>
            <!-- Default form login -->
        </div>
        </div>
        <div class="col-md-">
        </div>
</div>
{% endblock %}

contas/templates/contas/registros.html
<div class="list-group">
    <h3 class="list-group-item">
        Cursos
    </h3>
	{% for inscricao in cursos %}
				<a class="list-group-item list-group-item-action" href="{% url 'cursos:detalhe' inscricao.curso.slug %}">
				<span class="fa fa-book">&nbsp;</span>
				{{inscricao.curso.nome | slice:":35"}}
				</a>
	{% empty %}
	    <p class="text-danger">Nenhum curso encontrado.</p>
	{% endfor %}
</div>

contas/templates/contas/senha.html
{% extends 'contas/admin_cursos.html'%}
{% load bootstrap4 %}
{% block breadcrumb %}
{{block.super}}
<li class="breadcrumb-item"><a href="{% url 'cursos:anuncio' %}">Aulas</a></li>
{% endblock %}
{% block tema %}
<h1 class="text-center">Editar Perfil</h1>
{% endblock %}
{% block estudante %}
<br><br>
    <div class="row">
        <div class="offset-1 col-md-7">
            <form method="post" action="#">
                {% csrf_token %}
                {% bootstrap_form form layout='inline'%}
                {% buttons %}
                    <button type="submit" class="btn btn-success">Alterar Senha</button>
                    <a href="{% url 'contas:painel' %}"><button type="button" class="btn btn-danger">Cancelar</button></a>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}